In [1]:
import pandas as pd
from ckanapi import RemoteCKAN
import datetime
import time

scidm = RemoteCKAN('https://scidm.nchc.org.tw', apikey='API_KEY')

dataset = pd.read_csv('/Users/fish/Downloads/dataset.csv', header=None, names=['ip', 'dataset','download', 'date', 'size', 'request', 'user-agent'])
dataset_org = pd.read_csv('/Users/fish/Downloads/dataset-organization.csv', header=None, names = ['org', 'ip', 'dataset', 'download', 'date', 'size', 'requests', 'user-agent'])
dataset_group = pd.read_csv('/Users/fish/Downloads/dataset-group.csv', header=None, names=['group', 'ip', 'dataset','download', 'date', 'size', 'request', 'user-agent'])

In [2]:
dataset.head()

,ip,dataset,download,date,size,request,user-agent
0,66.249.71.10,False,False,20/Jun/2019:06:25:23 +0800,806,GET /robots.txt HTTP/1.0,Mozilla/5.0 (compatible; Googlebot/2.1; +http:...
1,66.249.71.10,False,False,20/Jun/2019:06:25:23 +0800,564,GET /rating/dataset/frg0606/1 HTTP/1.0,Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Bu...
2,66.249.71.11,False,False,20/Jun/2019:06:25:26 +0800,6464,GET /dataset/frg0606 HTTP/1.0,Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Bu...
3,40.77.167.163,60e0a685-9454-44e7-83e5-09a87264f04e,False,20/Jun/2019:06:30:51 +0800,7686,GET /dataset/nih-clinical-center-deeplesion/re...,Mozilla/5.0 (compatible; bingbot/2.0; +http://...
4,66.249.71.9,False,False,20/Jun/2019:06:32:53 +0800,806,GET /robots.txt HTTP/1.0,Mozilla/5.0 (compatible; Googlebot/2.1; +http:...

In [3]:
dataset_org.head()

,org,ip,dataset,download,date,size,requests,user-agent
0,False,66.249.71.10,False,False,20/Jun/2019:06:25:23 +0800,806,GET /robots.txt HTTP/1.0,Mozilla/5.0 (compatible; Googlebot/2.1; +http:...
1,False,66.249.71.10,False,False,20/Jun/2019:06:25:23 +0800,564,GET /rating/dataset/frg0606/1 HTTP/1.0,Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Bu...
2,False,66.249.71.11,False,False,20/Jun/2019:06:25:26 +0800,6464,GET /dataset/frg0606 HTTP/1.0,Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Bu...
3,aidm,40.77.167.163,60e0a685-9454-44e7-83e5-09a87264f04e,False,20/Jun/2019:06:30:51 +0800,7686,GET /dataset/nih-clinical-center-deeplesion/re...,Mozilla/5.0 (compatible; bingbot/2.0; +http://...
4,False,66.249.71.9,False,False,20/Jun/2019:06:32:53 +0800,806,GET /robots.txt HTTP/1.0,Mozilla/5.0 (compatible; Googlebot/2.1; +http:...

In [4]:
dataset_group.head()

,group,ip,dataset,download,date,size,request,user-agent
0,research,40.77.167.163,60e0a685-9454-44e7-83e5-09a87264f04e,False,20/Jun/2019:06:30:51 +0800,7686,GET /dataset/nih-clinical-center-deeplesion/re...,Mozilla/5.0 (compatible; bingbot/2.0; +http://...
1,research,5.45.207.63,0272e4d2-09d5-45e8-bbf0-c318fab67308,False,20/Jun/2019:06:52:04 +0800,9014,GET /dataset/open-images HTTP/1.0,Mozilla/5.0 (compatible; YandexBot/3.0; +http:...
2,research,66.102.8.136,c4b42f2d-ef31-4a13-b65a-75896396eb5c,False,20/Jun/2019:07:52:02 +0800,5359,GET /dataset/cargo-2000-freight-tracking-and-t...,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...
3,research,66.102.8.136,c4b42f2d-ef31-4a13-b65a-75896396eb5c,True,20/Jun/2019:07:52:06 +0800,1736,GET /dataset/cargo-2000-freight-tracking-and-t...,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...
4,research,179.6.201.94,c4b42f2d-ef31-4a13-b65a-75896396eb5c,False,20/Jun/2019:07:52:13 +0800,241,OPTIONS /dataset/c4b42f2d-ef31-4a13-b65a-75896...,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...

In [5]:
organization_data = dataset_org[dataset_org['org'] != 'False']
organization_data.head()

,org,ip,dataset,download,date,size,requests,user-agent
3,aidm,40.77.167.163,60e0a685-9454-44e7-83e5-09a87264f04e,False,20/Jun/2019:06:30:51 +0800,7686,GET /dataset/nih-clinical-center-deeplesion/re...,Mozilla/5.0 (compatible; bingbot/2.0; +http://...
15,ipgod-nchc,157.55.39.172,7f7a049e-a512-420b-a989-f2112e800a25,False,20/Jun/2019:06:46:12 +0800,12473,GET /dataset/315070700h-000015/resource/28efd6...,Mozilla/5.0 (compatible; bingbot/2.0; +http://...
18,aidm,5.45.207.63,0272e4d2-09d5-45e8-bbf0-c318fab67308,False,20/Jun/2019:06:52:04 +0800,9014,GET /dataset/open-images HTTP/1.0,Mozilla/5.0 (compatible; YandexBot/3.0; +http:...
25,ipgod-nchc,66.249.71.11,017355ba-98d2-4e63-a495-a63ff0bb3901,False,20/Jun/2019:06:57:55 +0800,5408,GET /dataset/e1307237-f7f5-4657-871c-1803f54aa...,Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Bu...
32,nchc_restricted,66.249.71.9,9cf1b8b6-3f05-48df-b510-be71492f1f7c,True,20/Jun/2019:07:07:12 +0800,995265,GET /dataset/9cf1b8b6-3f05-48df-b510-be71492f1...,Googlebot-Image/1.0

## 組織瀏覽次數

In [10]:
org_count = pd.DataFrame({'count' : organization_data.groupby(['org']).size()}).reset_index().sort_values('count', ascending=False)
org_count

                                org   count
10                       ipgod-nchc  231386
25                        tcia_data  108041
0                              aidm   81783
5               environment-quality   76441
16                  nchc-clean-data   62762
28  uci_machine_learning_repository   31772
6                    github-archive   31488
27                       tutorial01   29610
23                       postoffice   24130
21                             ntuh   20837
14                        narl-nspo   13097
7                           gov-wra   12900
3                        datamarket   10055
8                         i-scipark    8280
29                               v1    7212
9    information-security-open-data    6982
15                        narl-stpi    5284
26                              tmu    2774
11                 most-acad-upload    2697
24                      sinicaedutw    2249
4                               dot    2079
18                  nchc_restricted    1130
13                      most-upload     960
20                             noaa     837
22                    openstreetmap     241
17                    nchc-daas-net     198
19                nchcmanufacturing     197
1                   cdc-mohw-gov-tw     133
2                          civiliot     104
12                       most-iucrp      63

In [11]:
req_list = []

for i in org_count['org']:
    try:
        req_list.append(scidm.call_action('organization_show', {'id': i})['title'])
    except:
        req_list.append(i)
        pass

org_count['org'] = req_list
org_count

                                org   count
10                       政府開放資料彙整平台  231386
25                             TCIA  108041
0                       NCHC-人工智慧專區   81783
5               environment-quality   76441
16                NCHC-整合開放資料（國網洞見）   62762
28  UCI Machine Learning Repository   31772
6                    GitHub Archive   31488
27                     NCHC-教學示範展示區   29610
23                             各地郵政   24130
21                   國立臺灣大學醫療影像研究團隊   20837
14                           國家太空中心   13097
7                     經濟部水利署-水資料分享站   12900
3                          資料平台計劃專區   10055
8                            智慧科學園區    8280
29                  臺北榮民總醫院醫療影像研究團隊    7212
9                        資訊安全開放資料平台    6982
15                      科技政策研究與資訊中心    5284
26                   臺北醫學大學醫療影像研究團隊    2774
11                        科技部學研上傳專區    2697
24                      中央研究院相關之資料集    2249
4                          臺北市政府交通局    2079
18                         NCHC研究專區    1130
13                              科技部     960
20                             NOAA     837
22                    OpenStreetmap     241
17                         國網資料服務群網     198
19                        NCHC-智慧製造     197
1                        衛生福利部疾病管制署     133
2                      NCHC-民生公共物聯網     104
12                          科技部產學合作      63

In [22]:
org_count.to_csv('/Users/fish/Desktop/org_count.csv', index= False)

## 組織被下載次數

In [13]:
org_download = organization_data[organization_data['download'] != False]
org_download.head()

,org,ip,dataset,download,date,size,requests,user-agent
32,nchc_restricted,66.249.71.9,9cf1b8b6-3f05-48df-b510-be71492f1f7c,True,20/Jun/2019:07:07:12 +0800,995265,GET /dataset/9cf1b8b6-3f05-48df-b510-be71492f1...,Googlebot-Image/1.0
33,nchc_restricted,66.249.71.9,9cf1b8b6-3f05-48df-b510-be71492f1f7c,True,20/Jun/2019:07:07:13 +0800,1019138,GET /dataset/9cf1b8b6-3f05-48df-b510-be71492f1...,Googlebot-Image/1.0
34,nchc_restricted,66.249.71.10,9cf1b8b6-3f05-48df-b510-be71492f1f7c,True,20/Jun/2019:07:07:14 +0800,974153,GET /dataset/9cf1b8b6-3f05-48df-b510-be71492f1...,Googlebot-Image/1.0
38,ipgod-nchc,66.249.71.9,017355ba-98d2-4e63-a495-a63ff0bb3901,True,20/Jun/2019:07:10:13 +0800,1928,GET /dataset/e1307237-f7f5-4657-871c-1803f54aa...,Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Bu...
62,nchc_restricted,66.249.71.10,9cf1b8b6-3f05-48df-b510-be71492f1f7c,True,20/Jun/2019:07:31:05 +0800,995265,GET /dataset/9cf1b8b6-3f05-48df-b510-be71492f1...,Googlebot-Image/1.0

In [14]:
org_download_count = pd.DataFrame({'count' : org_download.groupby(['org']).size()}).reset_index().sort_values('count', ascending=False)
org_download_count

                                org  count
23                        tcia_data  40995
15                  nchc-clean-data  30522
10                       ipgod-nchc  19631
26  uci_machine_learning_repository  10773
0                              aidm  10250
5               environment-quality   9178
13                        narl-nspo   4955
8                         i-scipark   3463
3                        datamarket   2948
9    information-security-open-data   2921
21                       postoffice   2873
19                             ntuh   2167
27                               v1   2134
14                        narl-stpi   1776
25                       tutorial01   1564
7                           gov-wra   1130
6                    github-archive    949
22                      sinicaedutw    859
11                 most-acad-upload    634
4                               dot    614
24                              tmu    582
16                  nchc_restricted    152
18                             noaa    102
20                    openstreetmap     27
17                nchcmanufacturing     17
1                   cdc-mohw-gov-tw      8
12                      most-upload      4
2                          civiliot      4

In [15]:
down_list = []

for i in org_download_count['org']:
    try:
        down_list.append(scidm.call_action('organization_show', {'id': i})['title'])
    except:
        down_list.append(i)
        pass

org_download_count['org'] = down_list
org_download_count

                                org  count
23                             TCIA  40995
15                NCHC-整合開放資料（國網洞見）  30522
10                       政府開放資料彙整平台  19631
26  UCI Machine Learning Repository  10773
0                       NCHC-人工智慧專區  10250
5               environment-quality   9178
13                           國家太空中心   4955
8                            智慧科學園區   3463
3                          資料平台計劃專區   2948
9                        資訊安全開放資料平台   2921
21                             各地郵政   2873
19                   國立臺灣大學醫療影像研究團隊   2167
27                  臺北榮民總醫院醫療影像研究團隊   2134
14                      科技政策研究與資訊中心   1776
25                     NCHC-教學示範展示區   1564
7                     經濟部水利署-水資料分享站   1130
6                    GitHub Archive    949
22                      中央研究院相關之資料集    859
11                        科技部學研上傳專區    634
4                          臺北市政府交通局    614
24                   臺北醫學大學醫療影像研究團隊    582
16                         NCHC研究專區    152
18                             NOAA    102
20                    OpenStreetmap     27
17                        NCHC-智慧製造     17
1                        衛生福利部疾病管制署      8
12                              科技部      4
2                      NCHC-民生公共物聯網      4

In [23]:
org_download_count.to_csv('/Users/fish/Desktop/org_download_count.csv', index= False)

## 分類被瀏覽次數

In [17]:
group_count = pd.DataFrame({'count' : dataset_group.groupby(['group']).size()}).reset_index().sort_values('count', ascending=False)
group_count

                                                group   count
8                                            research  136217
1                                         environment   54770
3                                                life   41569
7                                   publicinformation   36222
4                                             medical   33417
9                                             traffic   26404
10                                              voice    6515
5                                       nchc_ai_bus01    2811
0                                               ai-ml    1137
2                                information-security     909
6   pacific-rim-application-and-grid-middleware-as...      90

In [18]:
group_name_list = []
for group_name in list(group_count['group']):
#     print(scidm.call_action('group_show', {'id': group_name})['title'])
    group_name_list.append(scidm.call_action('group_show', {'id': group_name})['title'])

group_count['group'] = group_name_list
group_count

     group   count
8       科研  136217
1       環境   54770
3       生活   41569
7     政府治理   36222
4       醫療   33417
9       交通   26404
10      語音    6515
5   AI企業列車    2811
0    AI-ML    1137
2     資訊安全     909
6   PRAGMA      90

In [24]:
group_count.to_csv('/Users/fish/Desktop/group_count.csv', index= False)

## 分類被下載次數

In [19]:
dataset_group_download = dataset_group[dataset_group['download'] != False]
dataset_group_download.head()

,group,ip,dataset,download,date,size,request,user-agent
3,research,66.102.8.136,c4b42f2d-ef31-4a13-b65a-75896396eb5c,True,20/Jun/2019:07:52:06 +0800,1736,GET /dataset/cargo-2000-freight-tracking-and-t...,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...
14,medical,140.109.125.68,661156b3-d357-465c-8967-b4baebde0209,True,20/Jun/2019:09:02:26 +0800,4734,GET /dataset/v1_mtss/resource/72dfbd3a-2958-4d...,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5...
15,medical,140.109.125.68,661156b3-d357-465c-8967-b4baebde0209,True,20/Jun/2019:09:02:37 +0800,159600,GET /dataset/661156b3-d357-465c-8967-b4baebde0...,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5...
16,medical,140.109.125.68,661156b3-d357-465c-8967-b4baebde0209,True,20/Jun/2019:09:02:39 +0800,159576,GET /dataset/661156b3-d357-465c-8967-b4baebde0...,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5...
24,publicinformation,36.230.202.19,6d123f0d-9f45-491e-8bb4-387b82d651d4,True,20/Jun/2019:10:24:08 +0800,121955,GET /dataset/6d123f0d-9f45-491e-8bb4-387b82d65...,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4...

In [20]:
group_count_download = pd.DataFrame({'count' : dataset_group_download.groupby(['group']).size()}).reset_index().sort_values('count', ascending=False)
group_count_download

                                                group  count
8                                            research  25080
1                                         environment  16164
3                                                life  11248
7                                   publicinformation   7485
4                                             medical   5620
9                                             traffic   3505
10                                              voice   2259
5                                       nchc_ai_bus01    461
2                                information-security    268
0                                               ai-ml    128
6   pacific-rim-application-and-grid-middleware-as...     47

In [21]:
group_down_list = []
for group_name in list(group_count_download['group']):
#     print(scidm.call_action('group_show', {'id': group_name})['title'])
    group_down_list.append(scidm.call_action('group_show', {'id': group_name})['title'])

group_count_download['group'] = group_down_list
group_count_download

     group  count
8       科研  25080
1       環境  16164
3       生活  11248
7     政府治理   7485
4       醫療   5620
9       交通   3505
10      語音   2259
5   AI企業列車    461
2     資訊安全    268
0    AI-ML    128
6   PRAGMA     47

In [25]:
group_count_download.to_csv('/Users/fish/Desktop/group_count_download.csv', index= False)